# Generated by Django 5.2 on 2025-04-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('vector', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]

# touched on 2025-06-13T18:50:05.987115Z
# touched on 2025-06-13T18:50:23.213585Z
# touched on 2025-06-13T18:50:37.928495Z