# Generated by Django 5.2 on 2025-04-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0004_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='vector',
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, to='lesson_plans.tag'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]

# touched on 2025-06-13T18:49:57.648069Z