# Generated by Django 5.2 on 2025-05-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0007_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-created_at']},
        ),
    ]

# touched on 2025-06-13T18:49:54.499324Z