# Generated by Django 5.2 on 2025-05-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0005_alter_userprofile_role'),
        ('lesson_plans', '0008_alter_chatmessage_options_alter_chatsession_options'),
    ]

    operations = [
    ]
