# Generated by Django 5.2 on 2025-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0010_chatsession_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='prompt_module/output_format/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]

# touched on 2025-06-13T18:50:03.181191Z
# touched on 2025-06-13T18:50:20.304720Z