# Generated by Django 5.2 on 2025-05-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0012_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PineconeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tag_names', models.JSONField(default=list)),
                ('vector_ids', models.JSONField()),
                ('chunk_count', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_plans.document')),
            ],
        ),
    ]
